package com.example.emerchantpay.data.constants

object UserRoomConstants {
    const val LOGIN = "login"
    const val ID = "id"
    const val NODE_ID = "node_id"
    const val AVATAR_URL = "avatar_url"
    const val GRAVATAR_ID = "gravatar_id"
    const val URL = "url"
    const val HTML_URL = "html_url"
    const val FOLLOWERS_URL = "followers_url"
    const val FOLLOWING_URL = "following_url"
    const val GISTS_URL = "gists_url"
    const val STARRED_URL = "starred_url"
    const val SUBSCRIPTIONS_URL = "subscriptions_url"
    const val ORGANIZATIONS_URL = "organizations_url"
    const val REPOS_URL = "repos_url"
    const val EVENTS_URL = "events_url"
    const val RECEIVED_EVENTS_URL = "received_events_url"
    const val TYPE = "type"
    const val SITE_ADMIN = "site_admin"
    const val NAME = "name"
    const val COMPANY = "company"
    const val BLOG = "blog"
    const val LOCATION = "location"
    const val EMAIL = "email"
    const val HIREABLE = "hireable"
    const val BIO = "bio"
    const val TWITTER_USERNAME = "twitter_username"
    const val PUBLIC_REPOS = "public_repos"
    const val PUBLIC_GISTS = "public_gists"
    const val FOLLOWERS = "followers"
    const val FOLLOWING = "following"
    const val CREATED_AT = "created_at"
    const val UPDATED_AT = "updated_at"
    const val FOLLOWED_BY_USER_ID = "followed_by_user_id"
}